A. REPRODUCIBLE NORMALIZATION PROBLEM

In [ ]:
import numpy as np

In [ ]:
np.random.seed(2112)
X = np.random.randint(10, 101, size=(5, 5))
print("Original Matrix (X) \n", X)

Original Matrix (X) 
 [[48 11 15 67 21]
 [11 41 13 66 24]
 [71 79 53 67 70]
 [77 35 91 19 96]
 [35 54 37 41 17]]


In [ ]:
X_normalized = (X - np.mean(X)) / np.std(X)
print("X_normalized Matrix\n",X_normalized)

X_normalized Matrix
 [[ 0.06340841 -1.36714726 -1.2124926   0.79801809 -0.98051059]
 [-1.36714726 -0.20723725 -1.28981993  0.75935442 -0.86451959]
 [ 0.95267275  1.26198209  0.25672675  0.79801809  0.91400909]
 [ 1.18465476 -0.43921926  1.72594609 -1.05783793  1.91926443]
 [-0.43921926  0.29539042 -0.36189192 -0.20723725 -1.13516526]]


In [ ]:
print("Mean of X =",np.mean(X))

Mean of X = 46.36


In [ ]:
print("Mean of X =",np.mean(X))

Mean of X = 46.36


In [ ]:
print("Mean of X_normalized =",np.mean(X_normalized))

Mean of X_normalized = 0.0


In [ ]:
print("Mean of X_normalized =",np.std(X_normalized))

Mean of X_normalized = 0.9999999999999999


In [ ]:
np.save("X_normalized.npy", X_normalized)

B. CUBES DIVISIBLE BY 4 PROBLEM

In [ ]:
X = np.arange(1,101)

print("X Matrix\n",X)

X Matrix
 [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [ ]:
C = X.reshape(10,10)
print("C Matrix (10x10)\n", C)

C Matrix (10x10)
 [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [ ]:
cubed = C**3
print("Cubed C Matrix\n", cubed)

Cubed C Matrix
 [[      1       8      27      64     125     216     343     512     729
     1000]
 [   1331    1728    2197    2744    3375    4096    4913    5832    6859
     8000]
 [   9261   10648   12167   13824   15625   17576   19683   21952   24389
    27000]
 [  29791   32768   35937   39304   42875   46656   50653   54872   59319
    64000]
 [  68921   74088   79507   85184   91125   97336  103823  110592  117649
   125000]
 [ 132651  140608  148877  157464  166375  175616  185193  195112  205379
   216000]
 [ 226981  238328  250047  262144  274625  287496  300763  314432  328509
   343000]
 [ 357911  373248  389017  405224  421875  438976  456533  474552  493039
   512000]
 [ 531441  551368  571787  592704  614125  636056  658503  681472  704969
   729000]
 [ 753571  778688  804357  830584  857375  884736  912673  941192  970299
  1000000]]


In [ ]:
Mod = cubed % 4
print("Modulo 4 of C Matrix\n", Mod)

Modulo 4 of C Matrix
 [[1 0 3 0 1 0 3 0 1 0]
 [3 0 1 0 3 0 1 0 3 0]
 [1 0 3 0 1 0 3 0 1 0]
 [3 0 1 0 3 0 1 0 3 0]
 [1 0 3 0 1 0 3 0 1 0]
 [3 0 1 0 3 0 1 0 3 0]
 [1 0 3 0 1 0 3 0 1 0]
 [3 0 1 0 3 0 1 0 3 0]
 [1 0 3 0 1 0 3 0 1 0]
 [3 0 1 0 3 0 1 0 3 0]]


In [ ]:
chk_mod = Mod == 0
print("Divisible by 4 checker\n", chk_mod)

Divisible by 4 checker
 [[False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]
 [False  True False  True False  True False  True False  True]]


In [ ]:
chk_cubed = cubed[chk_mod]
print("Cubed Checker\n", chk_cubed)

Cubed Checker
 [      8      64     216     512    1000    1728    2744    4096    5832
    8000   10648   13824   17576   21952   27000   32768   39304   46656
   54872   64000   74088   85184   97336  110592  125000  140608  157464
  175616  195112  216000  238328  262144  287496  314432  343000  373248
  405224  438976  474552  512000  551368  592704  636056  681472  729000
  778688  830584  884736  941192 1000000]


In [ ]:
np.save('div_by_4.npy', C)

C. ABOVE THE MEAN SQUARES PROBLEM

In [ ]:
X = np.arange(1,37)
print("First 36 Numbers\n", X)

First 36 Numbers
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


In [ ]:
S = X.reshape(6,6)
print("S Matrix (6x6)\n", S)

S Matrix (6x6)
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [ ]:
sqr = S**2
print("Squared S Matrix\n", sqr)

Squared S Matrix
 [[   1    4    9   16   25   36]
 [  49   64   81  100  121  144]
 [ 169  196  225  256  289  324]
 [ 361  400  441  484  529  576]
 [ 625  676  729  784  841  900]
 [ 961 1024 1089 1156 1225 1296]]


In [ ]:
Sum = np.sum(sqr)
print("Summation of Squared S Matrix =", Sum)

Summation of Squared S Matrix = 16206


In [ ]:
S_mean = Sum/36
print("Mean of S Matrix =", S_mean)

Mean of S Matrix = 450.1666666666667


In [ ]:
above_mean = sqr[sqr > S_mean]
print("Above Mean S Matrix\n", above_mean)

Above Mean S Matrix
 [ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296]


In [ ]:
Num_of_Elements = len(above_mean)
print("Number of Elements =", Num_of_Elements)

Number of Elements = 15


In [ ]:
np.save('above_mean.npy', above_mean)